export const COURSE_LIST_REQUEST = "COURSE_LIST_REQUEST";
export const COURSE_LIST_SUCCESS = "COURSE_LIST_SUCCESS";
export const COURSE_LIST_FAIL = "COURSE_LIST_FAIL";

export const COURSE_DETAIL_SUCCESS = 'COURSE_DETAILS_SUCCESS'
export const COURSE_DETAIL_REQUEST = 'COURSE_DETAILS_REQUEST'
export const COURSE_DETAIL_FAIL = 'COURSE_DETAILS_FAIL'

